# nginx/default.conf
server {
    listen 80;
    server_name localhost;
    root /var/www/public;
    
    index index.php index.html;


    location ~* ^/media/(.+)\.(jpg|jpeg|gif|png|ico|bmp|swf|doc|docx|pdf|xls|xlsx|rar|zip|tbz|tgz|7x|txt|woff|woff2|eot|svg|ttf)$ {
        root /var/www/;
        expires 1y;
    }


    #  location ~* \.(js|css|html)$ {
    #    root /var/www/;
    #    expires 1y;
    #  } 
    location ~* ^/media/(.+)\.(js|css|html)$ {
       	root /var/www/;
        expires 1y;
    }




    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;  # Имя сервиса из docker-compose
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
